#
# atmospheric
#

conventional:
  baseline_weights: &conv_base_weights mceq_conv_H4a_SIBYLL23c
  #additional:
  # hooks:
  #     OscillationsHook:
  #     spline_file: /data/user/jstettner/software/nuCraft/NuCraft_NuMu_ptype14SurvivialProb.pickle
  class: ConventionalAtmo
  #parameters: [conv_norm, delta_gamma, CR_grad, barr_h, barr_w, barr_z, barr_y]
  parameters: [conv_norm, delta_gamma]
  param_specifications:
    delta_gamma:
      baseline_weights: *conv_base_weights
prompt:
  baseline_weights: &prompt_base_weights mceq_pr_H4a_SIBYLL23c
  # baseline_weights: &prompt_base_weights cscd_atm_prompt
  class: PromptAtmo
  #additional:
  #   hooks: OscillationsHook
  parameters: [prompt_norm, delta_gamma, CR_grad]
  param_specifications:
    delta_gamma:
      baseline_weights: *prompt_base_weights
    CR_grad:
      baseline_weights: *prompt_base_weights
      alternative_weights: mceq_pr_GST4_SIBYLL23c

#
# Background Muons
#

muontemplate_2019MC:
  baseline_weights: powerlaw
  class: MuonTemplate
  parameters: [muon_norm]
  skip_syst: True
  additional:
    spline_file: /data/ana/Diffuse/AachenUpgoingTracks/sim/Splines/CorsikaMuonTemplate_spline.pickle

muontemplate_hobo:
  baseline_weights: powerlaw
  class: MuonTemplate
  parameters: [muon_norm]
  skip_syst: True
  additional:
    spline_file: /data/user/eganster/GlobalFit/NNMFit/resources/CorsikaMuonTemplate_SnowStorm.pickle

muontemplate:
  class: TemplateFlux
  parameters: [muon_norm]
  skip_syst: True
  additional:
    template_file: /data/user/eganster/GlobalFit/NNMFit/resources/templates/Tracks_CorsikaMuon.pickle

muontemplate_3D:
  class: TemplateFlux
  parameters: [muon_norm]
  skip_syst: True
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/muon/full_range_50_33_180_muonrate.pickle

muon:
  baseline_weights: muongun_conv_H4a_SIBYLL
  class: ConventionalAtmo
  parameters: [muongun_norm]
  skip_syst: False

#
# astro
#

astro:
  baseline_weights: powerlaw
  class: Powerlaw
  parameters: [astro_norm, gamma_astro]
  # hooks:
  #     NuTauCorrectionRatioHook:
  #     spline_file: /data/user/pfuerst/DiffuseExtensions/data/MC/nutau_nue_corrections/nutau_correction_IC86_pass2_fixedTauMC.pickle

astro_3flavor:
  baseline_weights: powerlaw
  class: Powerlaw
  parameters: [astro_norm, gamma_astro, astro_nue_ratio, astro_nutau_ratio]

astro_wcutoff:
  baseline_weights: powerlaw
  class: Powerlaw 
  parameters: [astro_norm, gamma_astro, cutoff_astro]

logparabola_astro:
  baseline_weights: powerlaw
  class: LogParabola
  parameters: [astro_parabola_norm, astro_parabola_a, astro_parabola_b]

brokenastro_fixed:
  baseline_weights: powerlaw
  class: BrokenPowerlaw_fixedBreak 
  parameters: [astro_norm, gamma_astro_second, gamma_astro_first]

piecewise_astro_5bin:
  baseline_weights: powerlaw
  class: PiecewisePowerlaw
  parameters: [piece1, piece2, piece3, piece4, piece5]

piecewise_astro_13bin:
  baseline_weights: powerlaw
  class: PiecewisePowerlaw
  parameters: [cscd_piece1, cscd_piece2, cscd_piece3, cscd_piece4, cscd_piece5, cscd_piece6, cscd_piece7, cscd_piece8, cscd_piece9, cscd_piece10, cscd_piece11, cscd_piece12,cscd_piece13]

#
# galactic
#

#
# analytic models
#

galactic_box:
  baseline_weights: powerlaw
  class: GalacticBox
  parameters: [galactic_norm, gamma_galactic]
  additional:
    reference_index: 2.
    width_deg: 10

#
# galactic splines
#

galacticspline_fermi:
  baseline_weights: fluxless_weight
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    reference_index: 2.
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/scipy_1.10.1/2.72_extrapol_Flux_pi0_decay_56_SNR_z4kpc_R20kpc_Ts150K_EBV5mag.npz

galacticspline_KRA_5:
  baseline_weights: powerlaw
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    reference_index: 2.
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/scipy_1.10.1/KRAgamma_5_DNNCascade_gal.npz

galacticspline_KRA_50:
  baseline_weights: powerlaw
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    reference_index: 2.
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/scipy_1.10.1/KRAgamma_50_DNNCascade_gal.npz

galacticspline_FM_const:
  baseline_weights: powerlaw
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    reference_index: 2.
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/scipy_1.10.1/FangMurase_Constant_Template_SPL_2.7_1_7.npz

galacticspline_FM_SNR:
  baseline_weights: powerlaw
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    reference_index: 2.
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/scipy_1.10.1/FangMurase_SNR_Template_SPL_2.7_1_7.npz

galacticspline_CRINGE:
  baseline_weights: powerlaw
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    reference_index: 2.
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/scipy_1.10.1/Neutrino_AAfrag_Galprop_256_Ferr_D_5.182_R_17.0_B_0.011_0.566_0.159_0.453_1.050_lb_0.711_2.571_4.234_5.898_s_0.063_0.752_0.167_0.218_gn_2.383_2.324_2.339_Ab_87526.0_3101.0_ge_2.359_2.869_2.545_lbe_0.680_1.663_gx_2.386_1.520_H_0_8_50.npz

galacticspline_test_new_format:
  baseline_weights: fluxless_weight
  class: GalacticSpline
  parameters: [galactic_norm]
  additional:
    spline_file: /data/user/jhellrung/NNMFit/templates/galactic_splines/healpy/CRINGE_original_c.pickle

#
# galactic templates
#

galactictemplate_fermi:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm]
  skip_syst: True
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/fermi.pickle

galactictemplate_kraGamma5:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/kra5.pickle

galactictemplate_kraGamma50:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/kra50.pickle

galactictemplate_FangMuraseSNR:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/fm_snr.pickle

galactictemplate_FangMuraseConstant:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/fm_const.pickle

galactictemplate_Cringe:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/cringe.pickle


#copy to inject different model
galactictemplate_fermi_inject:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm_inject]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/fermi.pickle

galactictemplate_kraGamma5_inject:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm_inject]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/kra5.pickle

galactictemplate_kraGamma50_inject:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm_inject]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/kra50.pickle

galactictemplate_FangMuraseSNR_inject:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm_inject]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/fm_snr.pickle

galactictemplate_FangMuraseConstant_inject:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm_inject]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/fm_const.pickle

galactictemplate_Cringe_inject:
  baseline_weights: powerlaw
  class: GalacticTemplate
  parameters: [galactic_norm_inject]
  additional:
    template_file: /data/user/jhellrung/NNMFit/templates/galactic_templates/cringe.pickle

#
# astro models
#

modelastro_BLLac:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials//polyCfg_padovani_BLLac_GammaNeutrino_03.pickle
    reference_index: 2.

modelastro_lowL_BLLac:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials//polyCfg_Tavecci_lowBLLacs_Novariations.pickle
    reference_index: 2.

modelastro_Winter_TDE:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Winter_TDE_Novariations.pickle
    reference_index: 2.

modelastro_Stecker_AGNcore:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Stecker_AGNcore_Novariations.pickle
    reference_index: 2.

modelastro_Murase_innerJet:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Murase_innerJet_Gamma20_torus.pickle
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Murase_innerJet_Gamma23_torus.pickle
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Murase_innerJet_Gamma23_BlazarZone.pickle
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Murase_innerJet_Gamma20_BlazarZone.pickle
    reference_index: 2.

modelastro_Murase_chokedJet:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Murase_chokedJet_No variations.pickle
    reference_index: 2.

modelastro_Liu_AGNWinds:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Liu_AGNwinds_gamma23.pickle
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Liu_AGNwinds_gamma21.pickle
    reference_index: 2.

modelastro_Biehl_UHECRSum:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Biehl_UHECR_SumModelB.pickle
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Biehl_UHECR_SumModelC.pickle
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Biehl_UHECR_SumModelA.pickle
    reference_index: 2.

modelastro_Kimura_LLAGN:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_kimuramurase_LLAGN_model_B4.pickle
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_kimuramurase_LLAGN_model_B1.pickle
    reference_index: 2.

modelastro_Senno_SFG:
  baseline_weights: powerlaw
  class: AstroPrediction 
  parameters: [modelastro_norm]
  additional:
    #astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Senno_SFG_HNSN_Diffusion_E13.pickle
    astro_pred_cfg: /data/user/jstettner/DiffuseExtensions/NNMFit/resources/configs/astro_predictions_polynomials/polyCfg_Senno_SFG_HNSN_Diffusion_E12.pickle
    reference_index: 2.


#fluxless
fluxless:
  class: Powerlaw
  baseline_weights: fluxless_weight
  parameters: [astro_norm]
