analysis_type: asimov
llh: PoissonLLH
detector_configs: [IC86_pass2_SnowStorm_DNNCascade]
input_params:
  gamma_astro: 2.52
  astro_norm: 1.8
  prompt_norm: 0.0
  conv_norm: 1.0
  galactic_norm: 4.7
  # all (other) nuisance parameters at default
